mailer:
  default_email: '/opt/app/secrets/DEFAULT_EMAIL'
  default_email_name: '/opt/app/secrets/DEFAULT_EMAIL_NAME'
  forgot_password_mail_template_id: '/opt/app/secrets/FORGOT_PASSWORD_MAIL_TEMPLATE_ID'

mongodb:
  uri: '/opt/app/secrets/MONGODB_URI'

temporal:
  server_address: '/opt/app/secrets/TEMPORAL_SERVER_ADDRESS'

web_app_host: '/opt/app/secrets/WEB_APP_HOST'

inspectlet:
  key: '/opt/app/secrets/INSPECTLET_KEY'

datadog:
  api_key: '/opt/app/secrets/DATADOG_API_KEY'
  site_name: '/opt/app/secrets/DATADOG_SITE'
  app_name: '/opt/app/secrets/DATADOG_APP_NAME'
  log_level: '/opt/app/secrets/DATADOG_LOG_LEVEL'

sendgrid:
  api_key: '/opt/app/secrets/SENDGRID_API_KEY'

twilio:
  account_sid: '/opt/app/secrets/TWILIO_ACCOUNT_SID'
  auth_token: '/opt/app/secrets/TWILIO_AUTH_TOKEN'
  messaging_service_sid: '/opt/app/secrets/TWILIO_MESSAGING_SERVICE_SID'

public:
  datadog:
    applicationId: '/opt/app/secrets/DATADOG_APPLICATION_ID'
    clientToken: '/opt/app/secrets/DATADOG_CLIENT_TOKEN'
    enabled: '/opt/app/secrets/DATADOG_ENABLED'
    env: '/opt/app/secrets/DATADOG_ENV'
    service: '/opt/app/secrets/DATADOG_SERVICE'
    sessionReplaySampleRate: '/opt/app/secrets/DATADOG_SESSION_REPLAY_SAMPLE_RATE'
    sessionSampleRate: '/opt/app/secrets/DATADOG_SESSION_SAMPLE_RATE'
    site: '/opt/app/secrets/DATADOG_SITE'
  default_otp:
    enabled: '/opt/app/secrets/DEFAULT_OTP_ENABLED'
    code: '/opt/app/secrets/DEFAULT_OTP_CODE'
    whitelisted_phone_number: '/opt/app/secrets/DEFAULT_OTP_WHITELISTED_PHONE_NUMBER'  # e.g., "9999999999"
