mongodb:
  uri: 'mongodb://localhost:27017/flask-react-template-test'

celery:
  broker_url: 'redis://localhost:6379/1'
  result_backend: 'redis://localhost:6379/1'

worker:
  health_check_url: 'http://localhost:8080/api/'

mailer:
  default_email: 'DEFAULT_EMAIL'
  default_email_name: 'DEFAULT_EMAIL_NAME'
  forgot_password_mail_template_id: 'FORGOT_PASSWORD_MAIL_TEMPLATE_ID'

sms:
  enabled: false

public:
  default_otp:
    enabled: false
    code: '1234'
