name: cd

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  deploy:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    concurrency:
      group: cd-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout app
        uses: actions/checkout@v3
        with:
          path: app

      - name: Checkout github-ci
        uses: actions/checkout@v3
        with:
          repository: jalantechnologies/github-ci
          path: platform
          ref: v3.3.0-alpha.9

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -e 's/^refs\/heads\///g')
          BRANCH_HASH=$(sha1sum < <(printf '%s' $BRANCH_NAME) | cut -c -15)
          echo "branch_hash=$(echo $BRANCH_HASH)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: build
        uses: ./platform/.github/actions/build
        with:
          app_name: flask-react-app
          tag: ${{ steps.extract_branch.outputs.branch_hash }}
          build_args: APP_ENV=preview
          context: app/.
          docker_registry: ${{ vars.DOCKER_REGISTRY }}
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          target_sha : ${{ github.sha }}
          target_repository : jalantechnologies/flask-react-template
          target_ref : refs/heads/main
          target_token : ${{ secrets.TRIVY_SCAN_TOKEN }}
      
      - name: Run Trivy scan on docker images
        id: trivy-docker
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'image'
          image-ref: '${{vars.DOCKER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/flask-react-app:${{steps.extract_branch.outputs.branch_hash}}'
          format: 'template'
          template: '@markdown.tpl'
          output: 'trivy-docker-report.md'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
    
      - name: Comment PR with docker image results
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: trivy-docker-report.md

      - name: Deploy to preview
        uses: ./platform/.github/actions/deploy
        with:
          app_name: flask-react-app
          app_env: preview
          app_hostname: '{1}.preview.platform.bettrhq.com'
          branch: ${{ github.event.pull_request.head.ref }}
          deploy_id: ${{ github.run_number }}
          deploy_root: app/lib/kube
          deploy_labels: gh/pr=${{ github.event.number }}
          deploy_image: ${{ steps.build.outputs.image_ref }}
          docker_registry: ${{ vars.DOCKER_REGISTRY }}
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
          do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
          doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
          pull_request_number: ${{  github.event.pull_request.number }}
          deploy_annotate_pr: "true"
