name: clean

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@1e27a09243327a4ed01d42a9bc54965436ac0ba4
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      hosting_provider: ${{ vars.HOSTING_PROVIDER }}
      app_name: flask-react-app
      app_env: preview
      branch: ${{ github.event.pull_request.head.ref }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      aws_cluster_name: ${{ vars.AWS_CLUSTER_NAME }}
      aws_region: ${{ vars.AWS_REGION }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}

  print-secret:
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: Print masked secret for proof
        run: |
          echo "AWS SECRET:"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
