name: clean_on_delete

on: delete

jobs:
  clean:
    if: github.event.ref_type == 'branch'
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@vikram/feat/add-aws-ecr-image-cleanup
    concurrency:
      group: ci-preview-${{ github.event.ref }}
      cancel-in-progress: true
    with:
      # ENV-BASED provider selection
      hosting_provider: 'AWS'  # 'DIGITAL_OCEAN' or 'AWS' (Hardcoded to AWS for testing)
      aws_region: 'us-east-1' # Hardcoded for testing
      app_name: flask-react-template
      app_env: preview
      branch: ${{ github.event.ref }}
      docker_registry: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com # Hardcoded to test AWS ECR and registry detection logic
      docker_username: ${{ vars.DOCKER_USERNAME }}
      aws_cluster_name: ${{ vars.AWS_CLUSTER_NAME }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
