name: clean

on:
  pull_request_target:
    types: [closed]

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@vikram/feat/add-aws-ecr-image-cleanup
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
<<<<<<< HEAD:.github/workflows/clean_on_pr_closed.yml
      hosting_provider: 'AWS'  # 'DIGITAL_OCEAN' or 'AWS' (Hardcoded to AWS for testing)
=======
      hosting_provider: ${{ vars.HOSTING_PROVIDER }}
>>>>>>> bc25c86 (Optimize CI/CD pipeline architecture (#434)):.github/workflows/clean.yml
      app_name: flask-react-template
      app_env: preview
      branch: ${{ github.event.pull_request.head.ref }}
      docker_registry: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com # Hardcoded to test AWS ECR and registry detection logic
      # docker_username: ${{ vars.DOCKER_USERNAME }}
      aws_cluster_name: ${{ vars.AWS_CLUSTER_NAME }}
      aws_region: 'us-east-1' # Hardcoded for testing
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      # docker_password: ${{ secrets.DOCKER_PASSWORD }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}